spring:
  sql:
    init:
      schema-locations:
        - classpath:/db/createSchema.sql
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      data-locations:
        - classpath:/db/createData.sql
server:
  port: 8080


---
spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      data-locations:
        - classpath:/db/createData2.sql
server:
  port: 8081
