spring:
  sql:
    init:
      schema-locations:
        - classpath:/db/WarehouseSchema.sql

---

spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      data-locations:
        - classpath:/db/populateWarehouseDev.sql

server:
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      data-locations:
        - classpath:/db/populateWarehouseProd.sql

server:
  port: 8080